apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    name: redmine
spec:
  replicas: 3
  selector:
    name: redmine
  template:
    metadata:
      labels:
        name: redmine
    spec:
      containers:
        - name: redmine
          image: gcr.io/bitnami-tutorials/redmine
          env:
            - name: DATABASE_NAME
              value: redmine_production
            - name: DATABASE_USER
              value: redmine
            - name: S3_BUCKET
              value: redmine-uploads
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: secrets
              mountPath: /etc/redmine-secrets
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 1
      volumes:
        - name: secrets
          secret:
            secretName: redmine-secrets
